### ISSUE TITLE
How should I use this loss function

### ISSUE THREAD

**Issue by jccmoing-bit** [aybora/yolov5Loss#1]
I just replaced the loss.py file the error happened: KeyError: 'LRM_ignore'

**Comment by aybora** [comment]
You also have to use given hyperparameter .yaml file.

**Comment by jccmoing-bit** [comment]
> You also have to use given hyperparameter .yaml file.
Thank you for your reply
Warning when starting training
ARNING: NMS time limit 10.0s exceeded
what causes this

**Comment by aybora** [comment]
Focal loss generally increases objectness score of the potential outputs, which means more input to fed into NMS, which slows your validation process and exceeding NMS time limit, especially in case you have many number of classes. You may try to increase the objectness threshold which is responsible feeding NMS.
