### ISSUE TITLE
problem calling bbox_iou

### ISSUE THREAD

**Issue by SV1367** [aybora/yolov5Loss#3]
File "/home/sergio/Programming/yolov5-ultralytics/utils/loss.py", line 161, in __call__
    iou = bbox_iou(pbox.T, tbox[i], x1y1x2y2=False, CIoU=True)  # iou(prediction, target)
TypeError: bbox_iou() got an unexpected keyword argument 'x1y1x2y2'

I am using yolov5 version: 6-1.322

**Comment by aybora** [comment]
Please use [this release](https://github.com/ultralytics/yolov5/releases/tag/v6.0).

**Comment by SV1367** [comment]
Thanks. I have used git checkout tags/v6.0 -b newbranch
It is training now
